# Generated by Django 4.2.26 on 2025-12-01 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Usuario"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=255, verbose_name="Contraseña"),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nombre completo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "db_table": 'uesvalle"."colaborador',
                "managed": True,
            },
        ),
    ]
