# Generated by Django 4.2.24 on 2025-11-04 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimEtnia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.TextField(verbose_name="Nombre de la etnia")),
            ],
            options={
                "verbose_name": "Etnia",
                "verbose_name_plural": "Etnias",
                "db_table": 'uesvalle"."dim_etnia',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimGrado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.TextField(verbose_name="Nombre del grado")),
            ],
            options={
                "verbose_name": "Grado",
                "verbose_name_plural": "Grados",
                "db_table": 'uesvalle"."dim_grado',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimJornada",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.TextField(verbose_name="Nombre de la jornada")),
            ],
            options={
                "verbose_name": "Jornada",
                "verbose_name_plural": "Jornadas",
                "db_table": 'uesvalle"."dim_jornada',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimModalidadPAE",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.TextField(verbose_name="Nombre de la modalidad")),
            ],
            options={
                "verbose_name": "Modalidad PAE",
                "verbose_name_plural": "Modalidades PAE",
                "db_table": 'uesvalle"."dim_modalidad_pae',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimMunicipio",
            fields=[
                (
                    "codigo_municipio",
                    models.TextField(
                        help_text="Código único DANE del municipio",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código DANE",
                    ),
                ),
                ("nombre", models.TextField(verbose_name="Nombre del municipio")),
                (
                    "codigo_departamento",
                    models.TextField(verbose_name="Código del departamento"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "db_table": 'uesvalle"."dim_municipio',
                "ordering": ["nombre"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DimNivel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.TextField(verbose_name="Nombre del nivel")),
            ],
            options={
                "verbose_name": "Nivel Educativo",
                "verbose_name_plural": "Niveles Educativos",
                "db_table": 'uesvalle"."dim_nivel',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ETLRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado en"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado en"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("queued", "En cola"),
                            ("running", "En ejecución"),
                            ("completed", "Completado"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Información adicional como conteos, errores, etc.",
                        verbose_name="Metadatos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución ETL",
                "verbose_name_plural": "Ejecuciones ETL",
                "db_table": 'uesvalle"."etl_run',
                "ordering": ["-started_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.TextField(verbose_name="Nombre de la institución")),
                ("dane_ie_id", models.TextField(blank=True, null=True, unique=True)),
                ("sed_ie_id", models.TextField(blank=True, null=True, unique=True)),
                (
                    "uesvalle_ie_id",
                    models.TextField(blank=True, null=True, unique=True),
                ),
                ("codigo_municipio", models.TextField(blank=True, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("estado", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "db_table": 'uesvalle"."institucion',
                "ordering": ["nombre"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sede_id", models.UUIDField(blank=True, null=True)),
                ("institucion_id", models.UUIDField(blank=True, null=True)),
                ("fecha", models.DateField()),
                ("programa", models.TextField(blank=True, null=True)),
                ("resultado", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "db_table": 'uesvalle"."visita',
                "ordering": ["-fecha"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["sede_id"], name="visita_sede_id_d0649e_idx"),
                    models.Index(
                        fields=["institucion_id"], name="visita_institu_51c891_idx"
                    ),
                    models.Index(fields=["fecha"], name="visita_fecha_190f88_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "institucion_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Institución"),
                ),
                ("nombre", models.TextField(verbose_name="Nombre de la sede")),
                ("dane_sede_id", models.TextField(blank=True, null=True)),
                ("sed_sede_id", models.TextField(blank=True, null=True)),
                ("uesvalle_sede_id", models.TextField(blank=True, null=True)),
                ("codigo_municipio", models.TextField(blank=True, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("geom", models.TextField(blank=True, null=True)),
                ("estado", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "db_table": 'uesvalle"."sede',
                "ordering": ["nombre"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["institucion_id"], name="sede_institu_a05390_idx"
                    ),
                    models.Index(
                        fields=["codigo_municipio"], name="sede_codigo__f791c6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaeAsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sede_id", models.UUIDField(verbose_name="Sede")),
                ("anio", models.PositiveIntegerField()),
                ("periodo", models.TextField(default="")),
                ("modalidad", models.TextField()),
                ("beneficiarios", models.PositiveIntegerField()),
                ("fuente", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asignación PAE",
                "verbose_name_plural": "Asignaciones PAE",
                "db_table": 'uesvalle"."pae_asignacion',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["sede_id", "anio"],
                        name="pae_asignac_sede_id_492f17_idx",
                    ),
                    models.Index(fields=["anio"], name="pae_asignac_anio_608a1f_idx"),
                ],
                "unique_together": {("sede_id", "anio", "periodo", "modalidad")},
            },
        ),
        migrations.CreateModel(
            name="FactMatriculaEtnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sede_id", models.UUIDField(verbose_name="Sede")),
                ("corte_fecha", models.DateField()),
                ("grupo_etnico", models.TextField(default="")),
                ("total_alumnos", models.PositiveIntegerField()),
                ("fuente", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Matrícula Étnica",
                "verbose_name_plural": "Matrículas Étnicas",
                "db_table": 'uesvalle"."fact_matricula_etnica',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["corte_fecha"], name="fact_matric_corte_f_0f671a_idx"
                    ),
                    models.Index(
                        fields=["sede_id"], name="fact_matric_sede_id_4f121e_idx"
                    ),
                ],
                "unique_together": {("sede_id", "corte_fecha", "grupo_etnico")},
            },
        ),
        migrations.CreateModel(
            name="FactMatricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sede_id", models.UUIDField(verbose_name="Sede")),
                ("corte_fecha", models.DateField()),
                ("nivel", models.TextField(default="")),
                ("grado", models.TextField(default="")),
                ("jornada", models.TextField(default="")),
                ("genero", models.TextField(default="")),
                ("total_alumnos", models.PositiveIntegerField()),
                ("fuente", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "db_table": 'uesvalle"."fact_matricula',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["corte_fecha"], name="fact_matric_corte_f_916ca3_idx"
                    ),
                    models.Index(
                        fields=["sede_id", "corte_fecha"],
                        name="fact_matric_sede_id_92aa05_idx",
                    ),
                ],
                "unique_together": {
                    ("sede_id", "corte_fecha", "nivel", "grado", "jornada", "genero")
                },
            },
        ),
        migrations.CreateModel(
            name="ETLFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nombre del archivo"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (.xlsx, .xls)"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de archivo",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Ruta del archivo"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamaño en bytes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "rows_processed",
                    models.IntegerField(default=0, verbose_name="Filas procesadas"),
                ),
                (
                    "rows_failed",
                    models.IntegerField(default=0, verbose_name="Filas fallidas"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cargado en"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Procesado en"
                    ),
                ),
                (
                    "etl_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="etl.etlrun",
                        verbose_name="Job ETL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo ETL",
                "verbose_name_plural": "Archivos ETL",
                "db_table": 'public"."etl_file',
                "ordering": ["-uploaded_at"],
                "managed": True,
            },
        ),
    ]
