# Generated by Django 4.2.24 on 2025-09-23 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimMunicipio",
            fields=[
                (
                    "codigo_municipio",
                    models.CharField(
                        help_text="Código único DANE del municipio",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código DANE",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=120, verbose_name="Nombre del municipio"
                    ),
                ),
                (
                    "codigo_departamento",
                    models.CharField(
                        max_length=2, verbose_name="Código del departamento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "db_table": "uesvalle.dim_municipio",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ETLRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado en"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado en"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En ejecución"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="running",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Información adicional como conteos, errores, etc.",
                        verbose_name="Metadatos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución ETL",
                "verbose_name_plural": "Ejecuciones ETL",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la institución"
                    ),
                ),
                (
                    "dane_ie_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "sed_ie_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "uesvalle_ie_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo_municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="etl.dimmunicipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "db_table": "uesvalle.institucion",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre de la sede"),
                ),
                (
                    "dane_sede_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sed_sede_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "uesvalle_sede_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo_municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="etl.dimmunicipio",
                    ),
                ),
                (
                    "institucion_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etl.institucion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "db_table": "uesvalle.sede",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("programa", models.CharField(blank=True, max_length=255, null=True)),
                ("resultado", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institucion_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="etl.institucion",
                    ),
                ),
                (
                    "sede_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="etl.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "db_table": "uesvalle.visita",
            },
        ),
        migrations.CreateModel(
            name="StgInstitucionMySQL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_data", models.JSONField(verbose_name="Datos crudos")),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etl_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.etlrun"
                    ),
                ),
            ],
            options={
                "verbose_name": "Staging MySQL",
                "verbose_name_plural": "Staging MySQL",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PaeAsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField()),
                ("periodo", models.CharField(default="", max_length=50)),
                ("modalidad", models.CharField(max_length=100)),
                ("beneficiarios", models.PositiveIntegerField()),
                ("fuente", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sede_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.sede"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación PAE",
                "verbose_name_plural": "Asignaciones PAE",
                "db_table": "uesvalle.pae_asignacion",
            },
        ),
        migrations.CreateModel(
            name="FactMatriculaEtnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corte_fecha", models.DateField()),
                ("grupo_etnico", models.CharField(default="", max_length=100)),
                ("total_alumnos", models.PositiveIntegerField()),
                ("fuente", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sede_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.sede"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula Étnica",
                "verbose_name_plural": "Matrículas Étnicas",
                "db_table": "uesvalle.fact_matricula_etnica",
            },
        ),
        migrations.CreateModel(
            name="FactMatricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corte_fecha", models.DateField()),
                ("nivel", models.CharField(default="", max_length=50)),
                ("grado", models.CharField(default="", max_length=50)),
                ("jornada", models.CharField(default="", max_length=50)),
                ("genero", models.CharField(default="", max_length=10)),
                ("total_alumnos", models.PositiveIntegerField()),
                ("fuente", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sede_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="etl.sede"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "db_table": "uesvalle.fact_matricula",
            },
        ),
        migrations.CreateModel(
            name="FactInstitucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_dane",
                    models.CharField(
                        help_text="Código único DANE de la institución",
                        max_length=20,
                        unique=True,
                        verbose_name="Código DANE",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la institución"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Inactivo", "Inactivo"),
                            ("Suspendido", "Suspendido"),
                            ("En Proceso", "En Proceso"),
                        ],
                        default="Activo",
                        max_length=40,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[("Oficial", "Oficial"), ("No Oficial", "No Oficial")],
                        max_length=20,
                        null=True,
                        verbose_name="Sector",
                    ),
                ),
                (
                    "zona",
                    models.CharField(
                        blank=True,
                        choices=[("Urbana", "Urbana"), ("Rural", "Rural")],
                        max_length=10,
                        null=True,
                        verbose_name="Zona",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "updated_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash para detectar cambios en los datos",
                        max_length=64,
                        verbose_name="Hash de actualización",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        default="mysql",
                        help_text="Sistema de donde proviene el registro (mysql, excel_a, excel_b)",
                        max_length=50,
                        verbose_name="Sistema fuente",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="etl.dimmunicipio",
                        verbose_name="Municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institución Educativa",
                "verbose_name_plural": "Instituciones Educativas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ETLMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extraction_duration", models.DurationField(blank=True, null=True)),
                (
                    "transformation_duration",
                    models.DurationField(blank=True, null=True),
                ),
                ("loading_duration", models.DurationField(blank=True, null=True)),
                ("records_extracted_mysql", models.IntegerField(default=0)),
                ("records_extracted_excel", models.IntegerField(default=0)),
                ("records_transformed", models.IntegerField(default=0)),
                ("records_loaded", models.IntegerField(default=0)),
                ("records_rejected", models.IntegerField(default=0)),
                ("data_quality_score", models.FloatField(blank=True, null=True)),
                ("memory_peak_mb", models.FloatField(blank=True, null=True)),
                ("cpu_time_seconds", models.FloatField(blank=True, null=True)),
                (
                    "etl_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="etl.etlrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métricas ETL",
                "verbose_name_plural": "Métricas ETL",
            },
        ),
        migrations.CreateModel(
            name="ETLError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("extraction", "Error de Extracción"),
                            ("transformation", "Error de Transformación"),
                            ("loading", "Error de Carga"),
                            ("validation", "Error de Validación"),
                            ("connection", "Error de Conexión"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_table",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("record_id", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField()),
                ("error_context", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "etl_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="etl.etlrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error ETL",
                "verbose_name_plural": "Errores ETL",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DimSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Código de sede"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre de la sede"),
                ),
                (
                    "institucion_codigo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código de institución",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="etl_dimsede_codigo_7464c7_idx"
                    ),
                    models.Index(
                        fields=["institucion_codigo"],
                        name="etl_dimsede_institu_d4a6c1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataQualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("completeness", "Completitud"),
                            ("uniqueness", "Unicidad"),
                            ("consistency", "Consistencia"),
                            ("validity", "Validez"),
                            ("accuracy", "Precisión"),
                        ],
                        max_length=20,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("check_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Aprobado"),
                            ("failed", "Falló"),
                            ("warning", "Advertencia"),
                        ],
                        max_length=10,
                    ),
                ),
                ("records_checked", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "etl_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="etl.etlrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Calidad",
                "verbose_name_plural": "Controles de Calidad",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=50, verbose_name="Tabla")),
                (
                    "record_id",
                    models.CharField(max_length=50, verbose_name="ID del registro"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("insert", "Inserción"),
                            ("update", "Actualización"),
                            ("delete", "Eliminación"),
                        ],
                        max_length=10,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Valores anteriores"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Valores nuevos"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "etl_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="etl.etlrun",
                        verbose_name="Ejecución ETL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Cambio",
                "verbose_name_plural": "Logs de Cambios",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="sede",
            index=models.Index(
                fields=["institucion_id"], name="uesvalle.se_institu_8b93b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sede",
            index=models.Index(
                fields=["codigo_municipio"], name="uesvalle.se_codigo__e86ed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paeasignacion",
            index=models.Index(
                fields=["sede_id", "anio"], name="uesvalle.pa_sede_id_25ede9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paeasignacion",
            unique_together={("sede_id", "anio", "periodo", "modalidad")},
        ),
        migrations.AlterUniqueTogether(
            name="factmatriculaetnica",
            unique_together={("sede_id", "corte_fecha", "grupo_etnico")},
        ),
        migrations.AddIndex(
            model_name="factmatricula",
            index=models.Index(
                fields=["corte_fecha"], name="uesvalle.fa_corte_f_d1c2df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factmatricula",
            index=models.Index(
                fields=["sede_id", "corte_fecha"], name="uesvalle.fa_sede_id_65617a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="factmatricula",
            unique_together={
                ("sede_id", "corte_fecha", "nivel", "grado", "jornada", "genero")
            },
        ),
        migrations.AddIndex(
            model_name="factinstitucion",
            index=models.Index(
                fields=["codigo_dane"], name="etl_factins_codigo__bf100e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factinstitucion",
            index=models.Index(fields=["estado"], name="etl_factins_estado_08d4fe_idx"),
        ),
        migrations.AddIndex(
            model_name="factinstitucion",
            index=models.Index(
                fields=["municipio", "estado"], name="etl_factins_municip_a5d001_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factinstitucion",
            index=models.Index(
                fields=["updated_hash"], name="etl_factins_updated_612e26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factinstitucion",
            index=models.Index(
                fields=["source_system"], name="etl_factins_source__c33c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factinstitucion",
            index=models.Index(
                fields=["latitud", "longitud"], name="etl_factins_latitud_d429dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etlerror",
            index=models.Index(
                fields=["etl_run", "error_type"], name="etl_etlerro_etl_run_118032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etlerror",
            index=models.Index(
                fields=["source_table"], name="etl_etlerro_source__7ffbca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualitycheck",
            index=models.Index(
                fields=["etl_run", "status"], name="etl_dataqua_etl_run_a8a454_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualitycheck",
            index=models.Index(
                fields=["table_name", "check_type"],
                name="etl_dataqua_table_n_8917d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changelog",
            index=models.Index(
                fields=["table_name", "record_id"],
                name="etl_changel_table_n_973071_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changelog",
            index=models.Index(
                fields=["etl_run", "action"], name="etl_changel_etl_run_108aeb_idx"
            ),
        ),
    ]
