# Generated by Django 4.2.24 on 2025-11-25 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0002_create_etl_file_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etlfile",
            options={
                "managed": False,
                "ordering": ["-uploaded_at"],
                "verbose_name": "Archivo ETL",
                "verbose_name_plural": "Archivos ETL",
            },
        ),
        migrations.AlterModelOptions(
            name="etlrun",
            options={
                "managed": False,
                "ordering": ["-started_at"],
                "verbose_name": "Ejecución ETL",
                "verbose_name_plural": "Ejecuciones ETL",
            },
        ),
        migrations.AlterModelOptions(
            name="visita",
            options={
                "managed": True,
                "ordering": ["-fechavisita"],
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
            },
        ),
        migrations.RemoveIndex(
            model_name="visita",
            name="visita_fecha_190f88_idx",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="observaciones",
        ),
        migrations.AddField(
            model_name="visita",
            name="apellidofuncionario",
            field=models.TextField(
                blank=True, null=True, verbose_name="Apellido del funcionario"
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="codigofuncionario",
            field=models.IntegerField(
                blank=True,
                help_text="Convertido a INT desde MySQL",
                null=True,
                verbose_name="Código del funcionario",
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="codigotipoobjeto",
            field=models.IntegerField(
                blank=True,
                help_text="Convertido a INT desde MySQL",
                null=True,
                verbose_name="Código tipo objeto",
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="conceptovisita",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Favorable"),
                    ("D", "Desfavorable"),
                    ("FCR", "Favorable con Requerimientos"),
                ],
                help_text="Debe ser F (Favorable), D (Desfavorable) o FCR (Favorable con Requerimientos)",
                max_length=3,
                null=True,
                verbose_name="Concepto de visita",
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="fechavisita",
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text="Formato DATE válido (YYYY-MM-DD), obligatorio",
                verbose_name="Fecha de visita",
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="motivovisita",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo de visita"
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="nombreactividad",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nombre de actividad"
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="nombrefuncionario",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nombre del funcionario"
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="nombretipoobjeto",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nombre tipo objeto"
            ),
        ),
        migrations.AddField(
            model_name="visita",
            name="observacion",
            field=models.TextField(blank=True, null=True, verbose_name="Observación"),
        ),
        migrations.AddField(
            model_name="visita",
            name="requerimientos",
            field=models.TextField(
                blank=True, null=True, verbose_name="Requerimientos"
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="codigo_municipio",
            field=models.TextField(
                blank=True,
                help_text="Debe existir en dim_municipio (FK)",
                null=True,
                verbose_name="Código municipio",
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="dane_ie_id",
            field=models.TextField(
                blank=True,
                help_text="11 dígitos - Viene de MySQL.codigodane o CSV.COD_DANE (si coincide)",
                null=True,
                unique=True,
                verbose_name="Código DANE IE",
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="estado",
            field=models.TextField(
                blank=True,
                default="ACTIVA",
                help_text="Default: ACTIVA",
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Incluye: origen (mysql/csv/ambos), campos_enriquecidos",
                verbose_name="Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="nombre",
            field=models.TextField(
                help_text="Nombre normalizado de la institución",
                verbose_name="Nombre de la institución",
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="sed_ie_id",
            field=models.TextField(
                blank=True, null=True, unique=True, verbose_name="ID SED IE"
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="uesvalle_ie_id",
            field=models.TextField(
                blank=True,
                help_text="OBLIGATORIO de MySQL.identificacion - Fuente de verdad",
                null=True,
                unique=True,
                verbose_name="ID UESValle IE",
            ),
        ),
        migrations.AlterField(
            model_name="visita",
            name="institucion_id",
            field=models.UUIDField(
                blank=True,
                help_text="FK obligatoria en producción - debe existir en tabla institucion",
                null=True,
                verbose_name="Institución",
            ),
        ),
        migrations.AlterField(
            model_name="visita",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Campos adicionales de MySQL no mapeados directamente",
                verbose_name="Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="visita",
            name="programa",
            field=models.TextField(
                blank=True,
                help_text="Usado para índice único de duplicados",
                null=True,
                verbose_name="Programa",
            ),
        ),
        migrations.AlterField(
            model_name="visita",
            name="resultado",
            field=models.TextField(blank=True, null=True, verbose_name="Resultado"),
        ),
        migrations.AlterField(
            model_name="visita",
            name="sede_id",
            field=models.UUIDField(
                blank=True,
                help_text="FK opcional - puede ser NULL si no hay sedes",
                null=True,
                verbose_name="Sede",
            ),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(
                fields=["uesvalle_ie_id"], name="institucion_uesvall_5eba9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(
                fields=["codigo_municipio"], name="institucion_codigo__807f66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visita",
            index=models.Index(
                fields=["fechavisita"], name="visita_fechavi_bcdc84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visita",
            index=models.Index(fields=["programa"], name="visita_program_edab2e_idx"),
        ),
        migrations.AddConstraint(
            model_name="visita",
            constraint=models.UniqueConstraint(
                fields=("sede_id", "fechavisita", "programa"),
                name="uq_visita_sede_fecha_programa",
            ),
        ),
    ]
