# Generated by Django 4.2.24 on 2025-09-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0002_initial"),
    ]

    operations = [
    ]
