# Generated by Django 4.2.24 on 2025-09-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0003_etlrun_dbtable"),
    ]

    operations = [
        migrations.RunSQL(
            sql=r'''
            CREATE SCHEMA IF NOT EXISTS uesvalle;
            CREATE TABLE IF NOT EXISTS uesvalle.etl_run (
                id BIGSERIAL PRIMARY KEY,
                started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                finished_at TIMESTAMPTZ NULL,
                status VARCHAR(30) NOT NULL DEFAULT 'running',
                meta JSONB NOT NULL DEFAULT '{}'::jsonb
            );
            ''',
            reverse_sql=r'''
            -- No reverse operation (table may be managed externally)
            ''',
        ),
    ]
