# Generated by Django 4.2.24 on 2025-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0005_notification"),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "uesvalle"."visita" DROP CONSTRAINT IF EXISTS "uq_visita_sede_fecha_programa";',
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="visita",
                    name="uq_visita_sede_fecha_programa",
                ),
            ]
        ),
        migrations.AddConstraint(
            model_name="visita",
            constraint=models.UniqueConstraint(
                fields=("institucion_id", "sede_id", "fechavisita", "programa"),
                name="uq_visita_sede_fecha_programa",
            ),
        ),
    ]
