# Generated by Django 4.2.24 on 2025-11-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0006_remove_visita_uq_visita_sede_fecha_programa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucion",
            name="dane_ie_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="11 dígitos - Viene de MySQL.codigodane o CSV.COD_DANE (si coincide)",
                null=True,
                verbose_name="Código DANE IE",
            ),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="sed_ie_id",
            field=models.TextField(blank=True, null=True, verbose_name="ID SED IE"),
        ),
        migrations.AlterField(
            model_name="institucion",
            name="uesvalle_ie_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="De MySQL.identificacion - Puede repetirse si hay diferentes sedes/niveles",
                null=True,
                verbose_name="ID UESValle IE",
            ),
        ),
        migrations.AddIndex(
            model_name="institucion",
            index=models.Index(
                fields=["uesvalle_ie_id", "nombre"],
                name="institucion_uesvall_71e258_idx",
            ),
        ),
    ]
